#!/bin/sh
apk add linux-edge linux-firmware-none
apk add bash ca-certificates eudev

### remove unused modules
rm -rf  /lib/modules/*/kernel/drivers/media
rm -rf  /lib/modules/*/kernel/drivers/gpu
rm -rf  /lib/modules/*/kernel/sound

### add udhcpc script
cat > /usr/share/udhcpc/default.script <<EOF
#!/bin/sh

# This script gets called by udhcpc to setup the network interfaces

mkdir -p /usr/share/udhcpc/
ip addr add \$ip/\$mask dev \$interface

if [ "\$router" ]; then
  ip route add default via \$router dev \$interface
fi

EOF
chmod 755 /usr/share/udhcpc/default.script
# Add some dns
echo "nameserver 1.1.1.1" > /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
# remove login message
> /etc/motd
