#!/bin/sh
apk add linux-edge linux-firmware-none
mkdir -p /usr/share/mkinitfs/ /etc/mkinitfs/
apk add bash ca-certificates eudev mkinitfs
echo 'features="ata base cdrom ext4 keymap kms lvm mmc nvme raid scsi squashfs usb virtio"' > /etc/mkinitfs/mkinitfs-live.conf
install /data/alpine-initramfs-init.sh /usr/share/mkinitfs/initramfs-init-live
# create new initrd
for kernel in $(ls /lib/modules) ; do
    depmod -a /lib/modules/$kernel
    mkinitfs -C gzip -i /usr/share/mkinitfs/initramfs-init-live -c /etc/mkinitfs/mkinitfs-live.conf -o /boot/initramfs-live "$kernel"
done
# remove login message
> /etc/motd
