#!/bin/sh
apk add networkmanager networkmanager-wifi networkmanager-tui
apk add dialog parted lsblk e2fsprogs cfdisk agetty bash
wget -O /tmp/netinstall.zip https://github.com/netinstall-combo/netinstall/archive/refs/heads/master.zip
cd /
unzip /tmp/netinstall.zip
mv netinstall-master /netinstall/
chmod 755 -R /netinstall
# install dropbear
apk add dropbear
yes "" | passwd
# change shell with netinstall combo main menu
echo "/netinstall/main.sh" >> /etc/shells
sed -i "/^root:x:*/d" /etc/passwd
echo "root:x:0:0:root:/:/netinstall/main.sh" >> /etc/passwd
