#!/bin/sh
apk add networkmanager networkmanager-wifi networkmanager-tui
wget -O /tmp/netinstall.zip https://github.com/netinstall-combo/netinstall/archive/refs/heads/master.zip
mkdir /netinstall
cd /netinstall
unzip /tmp/netinstall.zip
chmod 755 -R .
