#!/bin/sh

### remove unused directories
rm -rf /usr/share/i18n
rm -rf /usr/share/doc
rm -rf /usr/share/info
rm -rf /usr/share/help
rm -rf /usr/share/man
rm -rf /usr/share/locale
rm -rf /var/cache/apk/*
