#!/bin/sh
### remove unused modules
rm -rf  /lib/modules/*/kernel/drivers/media
rm -rf  /lib/modules/*/kernel/drivers/gpu
rm -rf  /lib/modules/*/kernel/sound

### remove unused directories
rm -rf /usr/share/i18n
rm -rf /usr/share/doc
rm -rf /usr/share/info
rm -rf /usr/share/help
rm -rf /usr/share/man
rm -rf /usr/share/locale

### remove vmlinuz
rm -rf /boot
