#!/busybox ash
# install yourself
/busybox clear
/busybox mkdir -p /bin
/busybox --install -s /bin
# mount directories
mkdir -p /dev /sys /proc /run /tmp /dev/pts
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts devpts /dev/pts
# create stdio symlinks
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr
# busybox mdev populate
/busybox mdev -s
# busybox networking
for dev in $(ls /sys/class/net) ; do
    echo "Network enable $dev"
    ip link set up dev $dev
    udhcpc -b -i $dev -s /etc/udhcpc/default.script 2>>/logs >>/logs &
done
wait
if cat /proc/cmdline | grep "ipv6=0" >/dev/null ; then
    echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
fi
if cat /proc/cmdline | grep "debug" >/dev/null ; then
    # spawn shell
    exec setsid cttyhack /bin/sh
fi
# run netinstall-combo
exec /bin/ash -c "setsid cttyhack /bootstrap || exec /bin/ash"
